### ISSUE TITLE
Build size

### ISSUE THREAD

**Issue by oliviertassinari** [STORIS/react-scrollbar-size#2]
A picture worth a thousand words.

@shawnmcknight shawnmcknight Please, can we do something about it 🙏 ?

![capture d ecran 2017-05-27 a 22 57 17](https://cloud.githubusercontent.com/assets/3165635/26524331/e53dddd0-432f-11e7-942f-a8b0d0e151ca.png)

*P.S. @sghall Great [resonance](https://sghall.github.io/resonance/#/examples/webpack-sunburst) project by the way* 👏

**Comment by sghall** [comment]
@oliviertassinari Haha.  Thanks, man!  I just pushed the [updated stats](https://sghall.github.io/resonance/#/examples/webpack-sunburst) from the next branch.  Those stats were pretty old. Looks like lodash.isequal is just 2.88% of the total now, but looks like you already have lodash/isEqual in there. 
<img width="718" alt="screen shot 2017-05-27 at 3 32 05 pm" src="https://cloud.githubusercontent.com/assets/4615775/26524771/4f3ecef2-42f3-11e7-9327-374e181def06.png">


<img width="637" alt="screen shot 2017-05-27 at 3 31 48 pm" src="https://cloud.githubusercontent.com/assets/4615775/26524767/3e65469c-42f3-11e7-93e7-107522ce5e53.png">

**Comment by shawnmcknight** [comment]
I've made several updates today and published a new version (1.0.2).  Most notably as it relates to this issue, I've eliminated usage of the isEqual function entirely but also updated to use the the base lodash module for the throttle calls.  This should keep it synchronized with material-ui's usage of lodash for throttling and eliminate any redundancies for that as well.

**Comment by oliviertassinari** [comment]
Awesome!
