### ISSUE TITLE
Declare react dependency as a peer dependency

### ISSUE THREAD

**Issue by jpaas** [STORIS/react-scrollbar-size#3]
Is there any change you can declare react as a peer dependency? Otherwise this causes the dreaded https://facebook.github.io/react/warnings/refs-must-have-owner.html error when used in a larger project.

**Comment by oliviertassinari** [comment]
I think that we will better off with the following peer dependency instead of dependencies
```json
    "lodash": "^4.17.4",
    "react": "^15.5.4",
    "react-event-listener": "^0.4.5"
```

**Comment by shawnmcknight** [comment]
> I think that we will better off with the following peer dependency instead of dependencies
>
>```json
>    "lodash": "^4.17.4",
>    "react": "^15.5.4",
>    "react-event-listener": "^0.4.5"

@oliviertassinari I agree on making **react** a peerDependency based on the originating issue.  **lodash** makes sense since it's so common and avoiding bundling additional versions unnecessarily seems like a good idea.  I'm trying to understand the reason behind the recommendation of **react-event-listener**, however.  Can you clarify why you are making a recommendation regarding that module?

**Comment by oliviertassinari** [comment]
> the reason behind the recommendation of react-event-listener

@shawnmcknight No strong reason for that recommandation, you can keep it as a dependency.

**Comment by shawnmcknight** [comment]
react and lodash have both been made peer dependencies rather than dependencies and a new version (2.0.0) was published.

**Comment by jpaas** [comment]
Thanks @shawnmcknight ! I'll ask the material-ui guys to pick it up.
