### ISSUE TITLE
Compatibility with React 16

### ISSUE THREAD

**Issue by jameswomack** [STORIS/react-scrollbar-size#5]
Projects that use React 16 could use this if the peer dep resolver was changed

**Comment by shawnmcknight** [comment]
Good call.  Peer dependency has been updated and release 2.0.2 has been published.

**Comment by shawnmcknight** [comment]
Should also alleviate issue reported in callemall/material-ui#8559.

**Comment by jameswomack** [comment]
Thank you!

**Comment by oliviertassinari** [comment]
@shawnmcknight Thanks!
