### ISSUE TITLE
React 16.9 warning: componentWillUpdate has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by Babettestam** [STORIS/react-scrollbar-size#8]
From React 17 this library won't work if this is not solved. Any change this can be fixed?

<img width="850" alt="Screenshot 2019-10-18 at 11 48 24" src="https://user-images.githubusercontent.com/3521402/67084552-7664fc80-f19d-11e9-9c5d-a02b21e9dfa8.png">

**Comment by shawnmcknight** [comment]
Fixed in #11.
